### ISSUE TITLE
Error running the demo-ng

### ISSUE THREAD

**Issue by ardiadrianadri** [sebawita/nativescript-mip-ble#2]
When I install the demo-ng in my Android phone and I try to open the app I get this error message:

```
java.lang.RuntimeException: Unable to create application
com.tns.NativeScriptApplication: com.tns.NativeScriptException:

Error calling module function

Error calling module function

Error: com.tns.NativeScriptException: Failed to find module:
"nativescript-mip-ble/bluetooth.scanner", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:244)
    com.tns.Runtime.run(Runtime.java:238)

com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)

android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)

android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5443)
    java.lang.reflect.Method.invoke(Native Method)

com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
File: "<unknown>, line: 1, column: 265

StackTrace:
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'',
file:'/data/data/org.nativescript.demong/files/app/scan/scan.component.js',
line: 2, column: 27
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'',
file:'/data/data/org.nativescript.demong/files/app/app.module.js', line: 8,
column: 24
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module:
"nativescript-mip-ble/bluetooth.scanner", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:244)
    com.tns.Runtime.run(Runtime.java:238)

com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)

android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)

android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5443)
    java.lang.reflect.Method.invoke(Native Method)

com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
File: "<unknown>, line: 1, column: 265

StackTrace:
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'',
file:'/data/data/org.nativescript.demong/files/app/scan/scan.component.js',
line: 2, column: 27
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'',
file:'/data/data/org.nativescript.demong/files/app/app.module.js', line: 8,
column: 24
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module:
"nativescript-mip-ble/bluetooth.scanner", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:244)
    com.tns.Runtime.run(Runtime.java:238)

com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)

android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)

android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5443)
    java.lang.reflect.Method.invoke(Native Method)

com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
File: "<unknown>, line: 1, column: 265

StackTrace:
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'',
file:'/data/data/org.nativescript.demong/files/app/scan/scan.component.js',
line: 2, column: 27
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'',
file:'/data/data/org.nativescript.demong/files/app/app.module.js', line: 8,
column: 24
Frame: function:'require', file:'', line: 1, column: 266

at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:4731)
at android.app.ActivityThread.-wrap1(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: com.tns.NativeScriptException:

Error calling module function

Error calling module function

Error: com.tns.NativeScriptException: Failed to find module:
"nativescript-mip-ble/bluetooth.scanner", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:244)
    com.tns.Runtime.run(Runtime.java:238)

com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)

android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)

android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5443)
    java.lang.reflect.Method.invoke(Native Method)

com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
File: "<unknown>, line: 1, column: 265

StackTrace:
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'',
file:'/data/data/org.nativescript.demong/files/app/scan/scan.component.js',
line: 2, column: 27
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'',
file:'/data/data/org.nativescript.demong/files/app/app.module.js', line: 8,
column: 24
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module:
"nativescript-mip-ble/bluetooth.scanner", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:244)
    com.tns.Runtime.run(Runtime.java:238)

com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)

android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)

android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5443)
    java.lang.reflect.Method.invoke(Native Method)

com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
File: "<unknown>, line: 1, column: 265

StackTrace:
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'',
file:'/data/data/org.nativescript.demong/files/app/scan/scan.component.js',
line: 2, column: 27
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'',
file:'/data/data/org.nativescript.demong/files/app/app.module.js', line: 8,
column: 24
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module:
"nativescript-mip-ble/bluetooth.scanner", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:244)
    com.tns.Runtime.run(Runtime.java:238)

com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)

android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)

android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5443)
    java.lang.reflect.Method.invoke(Native Method)

com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
File: "<unknown>, line: 1, column: 265

StackTrace:
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'',
file:'/data/data/org.nativescript.demong/files/app/scan/scan.component.js',
line: 2, column: 27
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'',
file:'/data/data/org.nativescript.demong/files/app/app.module.js', line: 8,
column: 24
Frame: function:'require', file:'', line: 1, column: 266

at com.tns.Runtime.runModule(Native Method)
at com.tns.Runtime.runModule(Runtime.java:244)
at com.tns.Runtime.run(Runtime.java:238)
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
at
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
... 8 more

--001a114b6bfef06dbe053dde38fa
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<p dir=3D"ltr">java.lang.RuntimeException: Unable to create application com=
.tns.NativeScriptApplication: com.tns.NativeScriptException: </p>
<p dir=3D"ltr">Error calling module function </p>
<p dir=3D"ltr">Error calling module function </p>
<p dir=3D"ltr">Error: com.tns.NativeScriptException: Failed to find module:=
 &quot;nativescript-mip-ble/bluetooth.scanner&quot;, relative to: /app/tns_=
modules/<br>
=C2=A0=C2=A0=C2=A0 com.tns.Module.resolvePathHelper(Module.java:220)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Module.resolvePath(Module.java:60)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.runModule(Native Method)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.runModule(Runtime.java:244)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.run(Runtime.java:238)<br>
=C2=A0=C2=A0=C2=A0 com.tns.NativeScriptApplication.onCreate(NativeScriptApp=
lication.java:17)<br>
=C2=A0=C2=A0=C2=A0 android.app.Instrumentation.callApplicationOnCreate(Inst=
rumentation.java:1036)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.handleBindApplication(Activit=
yThread.java:4728)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.-wrap1(ActivityThread.java)<b=
r>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread$H.handleMessage(ActivityThrea=
d.java:1415)<br>
=C2=A0=C2=A0=C2=A0 android.os.Handler.dispatchMessage(Handler.java:102)<br>
=C2=A0=C2=A0=C2=A0 android.os.Looper.loop(Looper.java:148)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.main(ActivityThread.java:5443=
)<br>
=C2=A0=C2=A0=C2=A0 java.lang.reflect.Method.invoke(Native Method)<br>
=C2=A0=C2=A0=C2=A0 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.r=
un(ZygoteInit.java:728)<br>
=C2=A0=C2=A0=C2=A0 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:=
618)<br>
File: &quot;&lt;unknown&gt;, line: 1, column: 265</p>
<p dir=3D"ltr">StackTrace: <br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br>
=09Frame: function:&#39;&#39;, file:&#39;/data/data/org.nativescript.demong=
/files/app/scan/scan.component.js&#39;, line: 2, column: 27<br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br>
=09Frame: function:&#39;&#39;, file:&#39;/data/data/org.nativescript.demong=
/files/app/app.module.js&#39;, line: 8, column: 24<br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br></p>
<p dir=3D"ltr">Error: com.tns.NativeScriptException: Failed to find module:=
 &quot;nativescript-mip-ble/bluetooth.scanner&quot;, relative to: /app/tns_=
modules/<br>
=C2=A0=C2=A0=C2=A0 com.tns.Module.resolvePathHelper(Module.java:220)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Module.resolvePath(Module.java:60)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.runModule(Native Method)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.runModule(Runtime.java:244)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.run(Runtime.java:238)<br>
=C2=A0=C2=A0=C2=A0 com.tns.NativeScriptApplication.onCreate(NativeScriptApp=
lication.java:17)<br>
=C2=A0=C2=A0=C2=A0 android.app.Instrumentation.callApplicationOnCreate(Inst=
rumentation.java:1036)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.handleBindApplication(Activit=
yThread.java:4728)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.-wrap1(ActivityThread.java)<b=
r>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread$H.handleMessage(ActivityThrea=
d.java:1415)<br>
=C2=A0=C2=A0=C2=A0 android.os.Handler.dispatchMessage(Handler.java:102)<br>
=C2=A0=C2=A0=C2=A0 android.os.Looper.loop(Looper.java:148)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.main(ActivityThread.java:5443=
)<br>
=C2=A0=C2=A0=C2=A0 java.lang.reflect.Method.invoke(Native Method)<br>
=C2=A0=C2=A0=C2=A0 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.r=
un(ZygoteInit.java:728)<br>
=C2=A0=C2=A0=C2=A0 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:=
618)<br>
File: &quot;&lt;unknown&gt;, line: 1, column: 265</p>
<p dir=3D"ltr">StackTrace: <br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br>
=09Frame: function:&#39;&#39;, file:&#39;/data/data/org.nativescript.demong=
/files/app/scan/scan.component.js&#39;, line: 2, column: 27<br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br>
=09Frame: function:&#39;&#39;, file:&#39;/data/data/org.nativescript.demong=
/files/app/app.module.js&#39;, line: 8, column: 24<br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br></p>
<p dir=3D"ltr">Error: com.tns.NativeScriptException: Failed to find module:=
 &quot;nativescript-mip-ble/bluetooth.scanner&quot;, relative to: /app/tns_=
modules/<br>
=C2=A0=C2=A0=C2=A0 com.tns.Module.resolvePathHelper(Module.java:220)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Module.resolvePath(Module.java:60)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.runModule(Native Method)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.runModule(Runtime.java:244)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.run(Runtime.java:238)<br>
=C2=A0=C2=A0=C2=A0 com.tns.NativeScriptApplication.onCreate(NativeScriptApp=
lication.java:17)<br>
=C2=A0=C2=A0=C2=A0 android.app.Instrumentation.callApplicationOnCreate(Inst=
rumentation.java:1036)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.handleBindApplication(Activit=
yThread.java:4728)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.-wrap1(ActivityThread.java)<b=
r>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread$H.handleMessage(ActivityThrea=
d.java:1415)<br>
=C2=A0=C2=A0=C2=A0 android.os.Handler.dispatchMessage(Handler.java:102)<br>
=C2=A0=C2=A0=C2=A0 android.os.Looper.loop(Looper.java:148)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.main(ActivityThread.java:5443=
)<br>
=C2=A0=C2=A0=C2=A0 java.lang.reflect.Method.invoke(Native Method)<br>
=C2=A0=C2=A0=C2=A0 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.r=
un(ZygoteInit.java:728)<br>
=C2=A0=C2=A0=C2=A0 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:=
618)<br>
File: &quot;&lt;unknown&gt;, line: 1, column: 265</p>
<p dir=3D"ltr">StackTrace: <br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br>
=09Frame: function:&#39;&#39;, file:&#39;/data/data/org.nativescript.demong=
/files/app/scan/scan.component.js&#39;, line: 2, column: 27<br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br>
=09Frame: function:&#39;&#39;, file:&#39;/data/data/org.nativescript.demong=
/files/app/app.module.js&#39;, line: 8, column: 24<br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br></p>
<p dir=3D"ltr">=09at android.app.ActivityThread.handleBindApplication(Activ=
ityThread.java:4731)<br>
=09at android.app.ActivityThread.-wrap1(ActivityThread.java)<br>
=09at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)<=
br>
=09at android.os.Handler.dispatchMessage(Handler.java:102)<br>
=09at android.os.Looper.loop(Looper.java:148)<br>
=09at android.app.ActivityThread.main(ActivityThread.java:5443)<br>
=09at java.lang.reflect.Method.invoke(Native Method)<br>
=09at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit=
.java:728)<br>
=09at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)<br>
Caused by: com.tns.NativeScriptException: </p>
<p dir=3D"ltr">Error calling module function </p>
<p dir=3D"ltr">Error calling module function </p>
<p dir=3D"ltr">Error: com.tns.NativeScriptException: Failed to find module:=
 &quot;nativescript-mip-ble/bluetooth.scanner&quot;, relative to: /app/tns_=
modules/<br>
=C2=A0=C2=A0=C2=A0 com.tns.Module.resolvePathHelper(Module.java:220)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Module.resolvePath(Module.java:60)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.runModule(Native Method)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.runModule(Runtime.java:244)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.run(Runtime.java:238)<br>
=C2=A0=C2=A0=C2=A0 com.tns.NativeScriptApplication.onCreate(NativeScriptApp=
lication.java:17)<br>
=C2=A0=C2=A0=C2=A0 android.app.Instrumentation.callApplicationOnCreate(Inst=
rumentation.java:1036)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.handleBindApplication(Activit=
yThread.java:4728)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.-wrap1(ActivityThread.java)<b=
r>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread$H.handleMessage(ActivityThrea=
d.java:1415)<br>
=C2=A0=C2=A0=C2=A0 android.os.Handler.dispatchMessage(Handler.java:102)<br>
=C2=A0=C2=A0=C2=A0 android.os.Looper.loop(Looper.java:148)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.main(ActivityThread.java:5443=
)<br>
=C2=A0=C2=A0=C2=A0 java.lang.reflect.Method.invoke(Native Method)<br>
=C2=A0=C2=A0=C2=A0 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.r=
un(ZygoteInit.java:728)<br>
=C2=A0=C2=A0=C2=A0 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:=
618)<br>
File: &quot;&lt;unknown&gt;, line: 1, column: 265</p>
<p dir=3D"ltr">StackTrace: <br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br>
=09Frame: function:&#39;&#39;, file:&#39;/data/data/org.nativescript.demong=
/files/app/scan/scan.component.js&#39;, line: 2, column: 27<br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br>
=09Frame: function:&#39;&#39;, file:&#39;/data/data/org.nativescript.demong=
/files/app/app.module.js&#39;, line: 8, column: 24<br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br></p>
<p dir=3D"ltr">Error: com.tns.NativeScriptException: Failed to find module:=
 &quot;nativescript-mip-ble/bluetooth.scanner&quot;, relative to: /app/tns_=
modules/<br>
=C2=A0=C2=A0=C2=A0 com.tns.Module.resolvePathHelper(Module.java:220)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Module.resolvePath(Module.java:60)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.runModule(Native Method)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.runModule(Runtime.java:244)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.run(Runtime.java:238)<br>
=C2=A0=C2=A0=C2=A0 com.tns.NativeScriptApplication.onCreate(NativeScriptApp=
lication.java:17)<br>
=C2=A0=C2=A0=C2=A0 android.app.Instrumentation.callApplicationOnCreate(Inst=
rumentation.java:1036)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.handleBindApplication(Activit=
yThread.java:4728)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.-wrap1(ActivityThread.java)<b=
r>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread$H.handleMessage(ActivityThrea=
d.java:1415)<br>
=C2=A0=C2=A0=C2=A0 android.os.Handler.dispatchMessage(Handler.java:102)<br>
=C2=A0=C2=A0=C2=A0 android.os.Looper.loop(Looper.java:148)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.main(ActivityThread.java:5443=
)<br>
=C2=A0=C2=A0=C2=A0 java.lang.reflect.Method.invoke(Native Method)<br>
=C2=A0=C2=A0=C2=A0 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.r=
un(ZygoteInit.java:728)<br>
=C2=A0=C2=A0=C2=A0 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:=
618)<br>
File: &quot;&lt;unknown&gt;, line: 1, column: 265</p>
<p dir=3D"ltr">StackTrace: <br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br>
=09Frame: function:&#39;&#39;, file:&#39;/data/data/org.nativescript.demong=
/files/app/scan/scan.component.js&#39;, line: 2, column: 27<br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br>
=09Frame: function:&#39;&#39;, file:&#39;/data/data/org.nativescript.demong=
/files/app/app.module.js&#39;, line: 8, column: 24<br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br></p>
<p dir=3D"ltr">Error: com.tns.NativeScriptException: Failed to find module:=
 &quot;nativescript-mip-ble/bluetooth.scanner&quot;, relative to: /app/tns_=
modules/<br>
=C2=A0=C2=A0=C2=A0 com.tns.Module.resolvePathHelper(Module.java:220)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Module.resolvePath(Module.java:60)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.runModule(Native Method)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.runModule(Runtime.java:244)<br>
=C2=A0=C2=A0=C2=A0 com.tns.Runtime.run(Runtime.java:238)<br>
=C2=A0=C2=A0=C2=A0 com.tns.NativeScriptApplication.onCreate(NativeScriptApp=
lication.java:17)<br>
=C2=A0=C2=A0=C2=A0 android.app.Instrumentation.callApplicationOnCreate(Inst=
rumentation.java:1036)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.handleBindApplication(Activit=
yThread.java:4728)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.-wrap1(ActivityThread.java)<b=
r>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread$H.handleMessage(ActivityThrea=
d.java:1415)<br>
=C2=A0=C2=A0=C2=A0 android.os.Handler.dispatchMessage(Handler.java:102)<br>
=C2=A0=C2=A0=C2=A0 android.os.Looper.loop(Looper.java:148)<br>
=C2=A0=C2=A0=C2=A0 android.app.ActivityThread.main(ActivityThread.java:5443=
)<br>
=C2=A0=C2=A0=C2=A0 java.lang.reflect.Method.invoke(Native Method)<br>
=C2=A0=C2=A0=C2=A0 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.r=
un(ZygoteInit.java:728)<br>
=C2=A0=C2=A0=C2=A0 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:=
618)<br>
File: &quot;&lt;unknown&gt;, line: 1, column: 265</p>
<p dir=3D"ltr">StackTrace: <br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br>
=09Frame: function:&#39;&#39;, file:&#39;/data/data/org.nativescript.demong=
/files/app/scan/scan.component.js&#39;, line: 2, column: 27<br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br>
=09Frame: function:&#39;&#39;, file:&#39;/data/data/org.nativescript.demong=
/files/app/app.module.js&#39;, line: 8, column: 24<br>
=09Frame: function:&#39;require&#39;, file:&#39;&#39;, line: 1, column: 266=
<br></p>
<p dir=3D"ltr">=09at com.tns.Runtime.runModule(Native Method)<br>
=09at com.tns.Runtime.runModule(Runtime.java:244)<br>
=09at com.tns.Runtime.run(Runtime.java:238)<br>
=09at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java=
:17)<br>
=09at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.j=
ava:1036)<br>
=09at android.app.ActivityThread.handleBindApplication(ActivityThread.java:=
4728)<br>
=09... 8 more<br>
</p>

--001a114b6bfef06dbe053dde38fa--
```

Seems that there is any dependency that the install task isn't installing

**Comment by sebawita** [comment]
There was a problem with the TypeScript not compiling correctly.
It should work now.
Can you try it out?
